ansible setup
----
- hosts: jenkins
  remote_user: ${YOUR_ACCOUNT}
  vars:
    file_system: davfs
    your_mount_dir: ${YOUR_MOUNT_DIR}
  tasks:
    - name: add directory
      file:
        path: "test-1"
        state: "directory"
    - name: Install svn1.7.22
      become: yes
      yum:
        name: http://opensource.wandisco.com/rhel/6/svn-1.7/RPMS/x86_64/subversion-1.7.22-1.x86_64.rpm
        state: present

    - name: ensure open JDK 1.6 is at the latest version
      become: yes
      yum:
        name: java-1.6.0-openjdk
        state: latest

    - name: get the Jenkins repository
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: add the Jenkins repository
      rpm_key:
        key: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

    - name: ensure jenkins is at the latest version
      become: yes
      yum:
        name: jenkins
        state: latest

    - name: ensure jenkins is running and enabled
      become: yes
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: mount directory to /var/test as davfs
      become: yes
      mount:
        state: mounted
        fstype: "{{ file_system }}"
        path: /var/test
        src: "{{ your_mount_dir }}"
